// =============================================================================
// Sample QA jobs (SYNTHETIC DEMO DATA)
// -----------------------------------------------------------------------------
// These entries are FICTIONAL and exist only to demonstrate the board and its
// eligibility engine. They are NOT real vacancies and the URLs are placeholders.
// The UI labels this feed as demo data. Replace it with a real adapter
// (see adapters.js) before using the board for actual job hunting.
//
// `daysAgo` is converted to a real posting date by SampleAdapter, so the demo
// always contains a spread of fresh and stale posts.
//
// The set intentionally includes jobs that SHOULD be filtered out (too old,
// min experience >= 3, wrong city, no post URL) so you can see the rules work.
// =============================================================================

export const SAMPLE_JOBS = [
  // ---- Eligible: NCR ------------------------------------------------------
  {
    id: "s1",
    title: "QA Automation Engineer",
    company: "Nimbus Software",
    experience: "0-3 years",
    location: "Noida",
    workMode: "Hybrid",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    daysAgo: 0,
    recruiterName: "Aditi Sharma",
    recruiterProfile: "https://www.linkedin.com/in/example-aditi-sharma",
    postUrl: "https://www.linkedin.com/posts/example-aditi-sharma_qa-hiring-noida",
    applicationMethod: "Email CV",
    applicationContact: "careers@nimbus.example.com",
    source: "recruiter",
  },
  {
    id: "s2",
    title: "SDET",
    company: "Finlytics",
    experience: "1-5 years",
    location: "Gurugram",
    workMode: "On-site",
    skills: ["Playwright", "TypeScript", "CI/CD", "Jenkins"],
    daysAgo: 2,
    recruiterName: "Rahul Verma",
    recruiterProfile: "https://www.linkedin.com/in/example-rahul-verma",
    postUrl: "https://www.linkedin.com/posts/example-rahul-verma_sdet-gurugram-hiring",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "technical recruiter",
  },
  {
    id: "s3",
    title: "Junior QA Engineer",
    company: "Nimbus Software",
    experience: "Fresher",
    location: "Greater Noida",
    workMode: "On-site",
    skills: ["Manual Testing", "SQL", "Jira"],
    daysAgo: 3,
    recruiterName: "Aditi Sharma",
    recruiterProfile: "https://www.linkedin.com/in/example-aditi-sharma",
    postUrl: "https://www.linkedin.com/posts/example-aditi-sharma_qa-fresher-greaternoida",
    applicationMethod: "DM recruiter",
    applicationContact: "",
    source: "recruiter",
  },
  {
    id: "s4",
    title: "Manual QA Engineer",
    company: "HealthSetu",
    experience: "2-8 years",
    location: "Delhi NCR",
    workMode: "Hybrid",
    skills: ["Manual Testing", "Postman", "Regression Testing"],
    daysAgo: 5,
    recruiterName: "Sneha Kapoor",
    recruiterProfile: "https://www.linkedin.com/in/example-sneha-kapoor",
    postUrl: "https://www.linkedin.com/posts/example-sneha-kapoor_manual-qa-delhi",
    applicationMethod: "Email CV",
    applicationContact: "jobs@healthsetu.example.com",
    source: "hr",
  },

  // ---- Eligible: Remote ---------------------------------------------------
  {
    id: "s5",
    title: "Automation Test Engineer",
    company: "CloudPeak",
    experience: "1-3 years",
    location: "Remote India",
    workMode: "Remote",
    skills: ["Cypress", "JavaScript", "API Testing", "GitHub"],
    daysAgo: 1,
    recruiterName: "Priya Nair",
    recruiterProfile: "https://www.linkedin.com/in/example-priya-nair",
    postUrl: "https://www.linkedin.com/posts/example-priya-nair_automation-remote-hiring",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "recruiter",
  },
  {
    id: "s6",
    title: "Software Tester",
    company: "Appsmith Labs",
    experience: "0-2 years",
    location: "Work From Home",
    workMode: "Remote",
    skills: ["Manual Testing", "Functional Testing", "Postman"],
    daysAgo: 4,
    recruiterName: "Priya Nair",
    recruiterProfile: "https://www.linkedin.com/in/example-priya-nair",
    postUrl: "https://www.linkedin.com/posts/example-priya-nair_software-tester-wfh",
    applicationMethod: "Email CV",
    applicationContact: "hiring@appsmithlabs.example.com",
    source: "recruiter",
  },
  {
    id: "s7",
    title: "QA Analyst",
    company: "Ledgerly",
    experience: "2-5 years",
    location: "Anywhere in India",
    workMode: "Remote",
    skills: ["SQL", "API Testing", "Regression Testing", "Jira"],
    daysAgo: 6,
    recruiterName: "Mohit Singh",
    recruiterProfile: "https://www.linkedin.com/in/example-mohit-singh",
    postUrl: "https://www.linkedin.com/posts/example-mohit-singh_qa-analyst-remote",
    applicationMethod: "DM recruiter",
    applicationContact: "",
    source: "hiring manager",
  },

  // ---- Excluded: min experience >= 3 -------------------------------------
  {
    id: "x1",
    title: "QA Engineer",
    company: "Stackforge",
    experience: "3-7 years",
    location: "Noida",
    workMode: "Hybrid",
    skills: ["Selenium", "Java"],
    daysAgo: 2,
    recruiterName: "Neha Gupta",
    recruiterProfile: "https://www.linkedin.com/in/example-neha-gupta",
    postUrl: "https://www.linkedin.com/posts/example-neha-gupta_qa-noida",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "recruiter",
  },
  {
    id: "x2",
    title: "Senior SDET",
    company: "Finlytics",
    experience: "5+ years",
    location: "Gurugram",
    workMode: "On-site",
    skills: ["Playwright", "CI/CD"],
    daysAgo: 1,
    recruiterName: "Rahul Verma",
    recruiterProfile: "https://www.linkedin.com/in/example-rahul-verma",
    postUrl: "https://www.linkedin.com/posts/example-rahul-verma_senior-sdet",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "technical recruiter",
  },

  // ---- Excluded: older than 7 days ---------------------------------------
  {
    id: "x3",
    title: "QA Automation Engineer",
    company: "OldPost Inc",
    experience: "0-3 years",
    location: "Delhi",
    workMode: "Hybrid",
    skills: ["Selenium", "Java"],
    daysAgo: 12,
    recruiterName: "Kiran Rao",
    recruiterProfile: "https://www.linkedin.com/in/example-kiran-rao",
    postUrl: "https://www.linkedin.com/posts/example-kiran-rao_qa-delhi",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "recruiter",
  },

  // ---- Excluded: wrong location ------------------------------------------
  {
    id: "x4",
    title: "QA Engineer",
    company: "Southbyte",
    experience: "1-5 years",
    location: "Bangalore",
    workMode: "On-site",
    skills: ["Selenium", "Java"],
    daysAgo: 2,
    recruiterName: "Deepa Menon",
    recruiterProfile: "https://www.linkedin.com/in/example-deepa-menon",
    postUrl: "https://www.linkedin.com/posts/example-deepa-menon_qa-bangalore",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "recruiter",
  },

  // ---- Excluded: not a QA role -------------------------------------------
  {
    id: "x5",
    title: "Backend Developer",
    company: "CloudPeak",
    experience: "0-3 years",
    location: "Remote India",
    workMode: "Remote",
    skills: ["Node.js", "SQL"],
    daysAgo: 1,
    recruiterName: "Priya Nair",
    recruiterProfile: "https://www.linkedin.com/in/example-priya-nair",
    postUrl: "https://www.linkedin.com/posts/example-priya-nair_backend-remote",
    applicationMethod: "Apply on post",
    applicationContact: "",
    source: "recruiter",
  },

  // ---- Excluded: not verifiable (no post URL) ----------------------------
  {
    id: "x6",
    title: "Test Engineer",
    company: "Ghostpost",
    experience: "0-3 years",
    location: "Noida",
    workMode: "Hybrid",
    skills: ["Manual Testing"],
    daysAgo: 1,
    recruiterName: "Unknown",
    recruiterProfile: "",
    postUrl: "",
    applicationMethod: "Unknown",
    applicationContact: "",
    source: "unknown",
  },
];
